// Knowledge Notes & Quick Takeaways Export Service for Clayverse AI
// Supports exporting to Plain Text (.txt), Markdown (.md), and Printable Formatted PDF

import { TAKEAWAYS_DATA, type TakeawayData } from '../components/QuickTakeaway';
import { LESSON_MODULES } from '../components/HomeCurriculumGrid';

export interface ExportOptions {
  includeTakeaways: boolean;
  includeStudentNotes: boolean;
  includeMentalModels: boolean;
  selectedLessonIds: string[]; // List of lesson IDs to include, or empty for all
  language: 'en' | 'hyd' | 'te';
  studentName?: string;
}

const NOTES_STORAGE_KEY = 'clay_student_knowledge_notes';

export function getStudentKnowledgeNotes(): Record<string, string> {
  try {
    if (typeof window !== 'undefined') {
      const stored = localStorage.getItem(NOTES_STORAGE_KEY);
      if (stored) {
        return JSON.parse(stored);
      }
    }
  } catch (e) {
    console.warn('Failed to load student notes:', e);
  }
  return {};
}

export function saveStudentKnowledgeNote(lessonId: string, noteText: string): Record<string, string> {
  const notes = getStudentKnowledgeNotes();
  if (!noteText.trim()) {
    delete notes[lessonId];
  } else {
    notes[lessonId] = noteText.trim();
  }

  try {
    if (typeof window !== 'undefined') {
      localStorage.setItem(NOTES_STORAGE_KEY, JSON.stringify(notes));
      window.dispatchEvent(new CustomEvent('clay_notes_updated', { detail: notes }));
    }
  } catch (e) {
    console.warn('Failed to save student note:', e);
  }
  return notes;
}

// Generate Plain Text (.txt)
export function generatePlainTextExport(options: ExportOptions): string {
  const isHyd = options.language === 'hyd' || options.language === 'te';
  const notes = getStudentKnowledgeNotes();
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const student = options.studentName || 'Clayverse AI Scholar';

  let output = '';
  output += `========================================================================\n`;
  output += `   CLAYVERSE AI • STUDENT STUDY GUIDE & QUICK TAKEAWAYS NOTEBOOK\n`;
  output += `========================================================================\n`;
  output += `Student: ${student}\n`;
  output += `Date of Export: ${dateStr}\n`;
  output += `Curriculum: Interactive AI Foundations to Advanced Architectures\n`;
  output += `========================================================================\n\n`;

  const lessonIds = options.selectedLessonIds.length > 0
    ? options.selectedLessonIds
    : LESSON_MODULES.map(m => m.id);

  lessonIds.forEach((id, index) => {
    const mod = LESSON_MODULES.find(m => m.id === id);
    const takeaway = TAKEAWAYS_DATA[id];
    const userNote = notes[id];

    if (!mod && !takeaway) return;

    const title = mod 
      ? (isHyd ? mod.titleHyd : mod.titleEn)
      : (takeaway ? (isHyd ? takeaway.titleHyd : takeaway.titleEn) : id);

    output += `------------------------------------------------------------------------\n`;
    output += `LESSON 0${index + 1}: ${title.toUpperCase()}\n`;
    output += `------------------------------------------------------------------------\n`;

    if (mod) {
      output += `Category: ${isHyd ? mod.categoryHyd : mod.categoryEn} | Read Time: ${mod.readTime}\n`;
      output += `Summary: ${isHyd ? mod.subtitleHyd : mod.subtitleEn}\n\n`;
    }

    if (options.includeTakeaways && takeaway) {
      output += `[ 💡 THE BIG PICTURE (TL;DR) ]\n`;
      output += `${isHyd ? takeaway.tldrHyd : takeaway.tldrEn}\n\n`;

      output += `[ 🔑 KEY LEARNING TAKEAWAYS ]\n`;
      const points = isHyd ? takeaway.keyPointsHyd : takeaway.keyPointsEn;
      points.forEach((pt, ptIdx) => {
        output += `  • ${pt}\n`;
      });
      output += `\n`;

      if (options.includeMentalModels) {
        output += `[ 🧠 MENTAL MODEL & RULE OF THUMB ]\n`;
        output += `"${isHyd ? takeaway.mentalModelHyd : takeaway.mentalModelEn}"\n\n`;
      }
    }

    if (options.includeStudentNotes && userNote) {
      output += `[ 📝 PERSONAL STUDY & KNOWLEDGE NOTES ]\n`;
      output += `${userNote}\n\n`;
    }

    output += `\n`;
  });

  output += `========================================================================\n`;
  output += `Generated by Clayverse AI - Keep learning every day to build your streak!\n`;
  output += `========================================================================\n`;

  return output;
}

// Generate Markdown (.md)
export function generateMarkdownExport(options: ExportOptions): string {
  const isHyd = options.language === 'hyd' || options.language === 'te';
  const notes = getStudentKnowledgeNotes();
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const student = options.studentName || 'Clayverse AI Scholar';

  let md = `# 🎓 Clayverse AI • Student Study Guide & Takeaways\n\n`;
  md += `> **Student:** ${student}  \n`;
  md += `> **Export Date:** ${dateStr}  \n`;
  md += `> **Curriculum:** Interactive Artificial Intelligence & Machine Learning\n\n`;
  md += `---\n\n`;

  const lessonIds = options.selectedLessonIds.length > 0
    ? options.selectedLessonIds
    : LESSON_MODULES.map(m => m.id);

  lessonIds.forEach((id, index) => {
    const mod = LESSON_MODULES.find(m => m.id === id);
    const takeaway = TAKEAWAYS_DATA[id];
    const userNote = notes[id];

    if (!mod && !takeaway) return;

    const title = mod 
      ? (isHyd ? mod.titleHyd : mod.titleEn)
      : (takeaway ? (isHyd ? takeaway.titleHyd : takeaway.titleEn) : id);

    md += `## 📚 Lesson 0${index + 1}: ${title}\n\n`;

    if (mod) {
      md += `* **Category:** \`${isHyd ? mod.categoryHyd : mod.categoryEn}\`\n`;
      md += `* **Estimated Study Time:** ${mod.readTime}\n`;
      md += `* **Overview:** ${isHyd ? mod.subtitleHyd : mod.subtitleEn}\n\n`;
    }

    if (options.includeTakeaways && takeaway) {
      md += `### 💡 The Big Picture (TL;DR)\n`;
      md += `> ${isHyd ? takeaway.tldrHyd : takeaway.tldrEn}\n\n`;

      md += `### 🔑 Key Learning Takeaways\n`;
      const points = isHyd ? takeaway.keyPointsHyd : takeaway.keyPointsEn;
      points.forEach(pt => {
        md += `- ${pt}\n`;
      });
      md += `\n`;

      if (options.includeMentalModels) {
        md += `### 🧠 Mental Model Formula\n`;
        md += `\`\`\`text\n${isHyd ? takeaway.mentalModelHyd : takeaway.mentalModelEn}\n\`\`\`\n\n`;
      }
    }

    if (options.includeStudentNotes && userNote) {
      md += `### 📝 Personal Knowledge Notes\n`;
      md += `${userNote}\n\n`;
    }

    md += `---\n\n`;
  });

  return md;
}

// Download file utility
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// Trigger Print / PDF Export Window
export function exportPrintablePdf(options: ExportOptions) {
  const isHyd = options.language === 'hyd' || options.language === 'te';
  const notes = getStudentKnowledgeNotes();
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  const student = options.studentName || 'Clayverse AI Scholar';

  const lessonIds = options.selectedLessonIds.length > 0
    ? options.selectedLessonIds
    : LESSON_MODULES.map(m => m.id);

  let lessonsHtml = '';

  lessonIds.forEach((id, index) => {
    const mod = LESSON_MODULES.find(m => m.id === id);
    const takeaway = TAKEAWAYS_DATA[id];
    const userNote = notes[id];

    if (!mod && !takeaway) return;

    const title = mod 
      ? (isHyd ? mod.titleHyd : mod.titleEn)
      : (takeaway ? (isHyd ? takeaway.titleHyd : takeaway.titleEn) : id);

    lessonsHtml += `
      <div class="lesson-card">
        <div class="lesson-header">
          <span class="lesson-badge">Lesson 0${index + 1}</span>
          <span class="lesson-category">${mod ? (isHyd ? mod.categoryHyd : mod.categoryEn) : 'Curriculum'}</span>
          <h2 class="lesson-title">${title}</h2>
          ${mod ? `<p class="lesson-subtitle">${isHyd ? mod.subtitleHyd : mod.subtitleEn}</p>` : ''}
        </div>

        ${options.includeTakeaways && takeaway ? `
          <div class="takeaway-section">
            <div class="tldr-box">
              <strong style="color:#D97706; display:block; margin-bottom:4px; font-size:12px; text-transform:uppercase;">
                💡 The Big Picture (TL;DR)
              </strong>
              <p style="margin:0; font-size:14px; line-height:1.5;">
                ${isHyd ? takeaway.tldrHyd : takeaway.tldrEn}
              </p>
            </div>

            <div style="margin-top:12px;">
              <strong style="font-size:12px; text-transform:uppercase; color:#4B5563; display:block; margin-bottom:6px;">
                🔑 Key Learning Takeaways:
              </strong>
              <ul style="margin:0; padding-left:18px; font-size:13px; line-height:1.6; color:#1F2937;">
                ${(isHyd ? takeaway.keyPointsHyd : takeaway.keyPointsEn).map(pt => `<li>${pt}</li>`).join('')}
              </ul>
            </div>

            ${options.includeMentalModels ? `
              <div class="mental-model-box">
                <span style="font-weight:bold; font-size:11px; text-transform:uppercase; color:#B45309; display:block; margin-bottom:2px;">
                  🧠 Mental Model & Rule of Thumb:
                </span>
                <span style="font-style:italic; font-size:13px; color:#1F2937;">
                  "${isHyd ? takeaway.mentalModelHyd : takeaway.mentalModelEn}"
                </span>
              </div>
            ` : ''}
          </div>
        ` : ''}

        ${options.includeStudentNotes && userNote ? `
          <div class="notes-section">
            <strong style="font-size:12px; text-transform:uppercase; color:#2563EB; display:block; margin-bottom:4px;">
              📝 Student Personal Knowledge Notes:
            </strong>
            <p style="margin:0; font-size:13px; line-height:1.5; color:#1E3A8A; white-space:pre-wrap;">
              ${userNote}
            </p>
          </div>
        ` : ''}
      </div>
    `;
  });

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to generate the printable PDF document.');
    return;
  }

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>Clayverse AI - Knowledge Notes & Takeaways (${dateStr})</title>
        <style>
          @page {
            margin: 15mm 15mm 15mm 15mm;
            size: A4 portrait;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
            color: #111827;
            background: #fff;
            margin: 0;
            padding: 20px;
            font-size: 13px;
            line-height: 1.5;
          }
          .header {
            border-bottom: 2px solid #D97706;
            padding-bottom: 12px;
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
            align-items: flex-end;
          }
          .logo-title {
            font-size: 24px;
            font-weight: 900;
            color: #1F2937;
            margin: 0;
            letter-spacing: -0.5px;
          }
          .logo-sub {
            font-size: 11px;
            color: #D97706;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
          }
          .meta-info {
            text-align: right;
            font-size: 11px;
            color: #6B7280;
          }
          .lesson-card {
            border: 1px solid #E5E7EB;
            border-radius: 12px;
            padding: 16px;
            margin-bottom: 20px;
            page-break-inside: avoid;
            background: #FAFAFA;
          }
          .lesson-header {
            margin-bottom: 12px;
          }
          .lesson-badge {
            display: inline-block;
            background: #1F2937;
            color: #fff;
            font-size: 10px;
            font-weight: bold;
            padding: 2px 8px;
            border-radius: 6px;
            text-transform: uppercase;
          }
          .lesson-category {
            font-size: 11px;
            font-weight: bold;
            color: #D97706;
            margin-left: 8px;
            text-transform: uppercase;
          }
          .lesson-title {
            font-size: 17px;
            font-weight: 800;
            margin: 6px 0 2px 0;
            color: #111827;
          }
          .lesson-subtitle {
            font-size: 12px;
            color: #6B7280;
            margin: 0;
          }
          .takeaway-section {
            background: #fff;
            border: 1px solid #F3F4F6;
            border-radius: 8px;
            padding: 12px;
            margin-top: 8px;
          }
          .tldr-box {
            background: #FFFBEB;
            border-left: 3px solid #D97706;
            padding: 10px;
            border-radius: 6px;
            margin-bottom: 10px;
          }
          .mental-model-box {
            background: #FEF3C7;
            border-radius: 6px;
            padding: 8px 12px;
            margin-top: 10px;
          }
          .notes-section {
            background: #EFF6FF;
            border: 1px solid #BFDBFE;
            border-radius: 8px;
            padding: 12px;
            margin-top: 10px;
          }
          .footer {
            text-align: center;
            font-size: 10px;
            color: #9CA3AF;
            margin-top: 30px;
            border-top: 1px solid #E5E7EB;
            padding-top: 10px;
          }
          @media print {
            body { padding: 0; }
            .no-print { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="logo-title">Clayverse AI</h1>
            <span class="logo-sub">Student Knowledge Notes & Quick Takeaways</span>
          </div>
          <div class="meta-info">
            <div><strong>Student:</strong> ${student}</div>
            <div><strong>Export Date:</strong> ${dateStr}</div>
            <div><strong>Curriculum:</strong> 9 Mastery Chapters</div>
          </div>
        </div>

        ${lessonsHtml}

        <div class="footer">
          Clayverse AI • Empowering learners with intuitive, pattern-based AI concepts. Generated for offline study.
        </div>

        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
    </html>
  `);
  printWindow.document.close();
}
